#!/bin/sh

vm=$1

if [ -z "$vm" ]
then
	echo "Usage: $0 <vm name>" >&2
	exit 1
fi	

if index=$(awk -vvm=$vm 'BEGIN { last=-1;} $1 == "<none>" { found=1; print $2; exit} $2 ~ /^[0-9]+$/ {last=$2} END { if (!found) { print last + 1; exit(1); } }' /usr/vms/nmdm.conf)
then
	sed -i.bak -r -e "s/^<none> $index\$/$vm $index/" /usr/vms/nmdm.conf
else
	echo "$vm $index" >> /usr/vms/nmdm.conf
fi

echo $index
