#!/bin/sh

AddHostEntry() 
{
    vm=$1

    lockf /tmp/conserver.lck sed -i ".bak" -e "/$vm/d" /usr/local/etc/conserver/VMs.conf
    echo "console $vm { include nmdm; device /dev/nmdm${2}B; } " | \
        lockf /tmp/conserver.lck tee -a /usr/local/etc/conserver/VMs.conf > /dev/null

    # Reload the entries
    sudo /usr/local/etc/rc.d/conserver reload
}

scriptdir=$(dirname $(realpath $0))
memsize="2048"
ncpu=2
buildtype=official
arch=amd64
swap=none
unset vmname branch image user

while getopts "b:C:i:n:N:m:M:S:t:u:" o
do
	case "$o"
	in
	b)
		branch="$OPTARG"
		;;
	i)
		image="$OPTARG"
		;;
	M)
		memsize="$OPTARG"
		;;
	m)
		arch="$OPTARG"
		;;
	N)
		ncpu="$OPTARG"
		;;
	n)
		vmname="$OPTARG"
		;;
	S)
		swap="$OPTARG"
		;;
	u)
		user="$OPTARG"
		;;
	esac
done

if [ -n "$branch" -a -z "$image" ]
then
	if [ -z "$user" ]
	then
		image="$(realpath /vmimages/official/$arch/$branch/LATEST)"
	else
		image="$(realpath /vmimages/user/$user/$arch/$branch/LATEST)"
	fi
fi

shift $(($OPTIND - 1))
OPTIND=1

if [ -n "$1" ]
then
	echo "Unrecognized argument $1"
	exit 1
fi

if [ ! -f "$image" ]
then
	echo "Image $image does not exist"
	exit 1
fi

if [ "$arch" = amd64 ]
then
	ostype="FreeBSD_64"
elif [ "$arch" = i386 ]
then
	ostype="FreeBSD"
else
	echo "Unknown architecture $arch"
	exit 1
fi

if ! echo "$swap" | egrep -q '^(auto|none|[0-9]+)$'
then
	echo "Unrecognized swap size $swap"
	exit 1
fi

if [ "$swap" = auto ]
then
	swap=$memsize
fi

if [ -z "$vmname" ]
then
	echo "-n option is mandatory" >&2
	exit 1
fi

if [ -d /usr/local/vmrc/vm/$vmname ]
then
	echo "VM $vmname already exists" >&2
	exit 1
fi

if ! expr "$vmname" : "[a-zA-Z0-9\-][a-zA-Z0-9\-]*$" > /dev/null
then
	echo "$vmname is not a valid host name" >&2
	exit 1
fi

set -e

vmdir=/usr/local/vmrc/vm/$vmname
mkdir $vmdir
mac=$(lockf /tmp/dnsmasq.lck $scriptdir/allocate_mac $vmname)
nmdm=$(lockf /tmp/nmdm.lck $scriptdir/allocate_nmdm $vmname)

libvirt_tmp=`mktemp`

cat - > $libvirt_tmp <<EOF
<domain type='bhyve'>
    <name>$vmname</name>
    <memory unit='MiB'>$memsize</memory>
    <currentMemory unit='MiB'>$memsize</currentMemory>
    <vcpu>$ncpu</vcpu>
    <os>
       <type>hvm</type>
    </os>
    <features>
      <apic/>
      <acpi/>
    </features>
    <clock offset='utc'/>
    <on_poweroff>destroy</on_poweroff>
    <on_reboot>restart</on_reboot>
    <on_crash>destroy</on_crash>
    <devices>
      <disk type='file'>
        <driver name='file' type='raw'/>
        <source file='$vmdir/$vmname.img'/>
        <target dev='hda' bus='sata'/>
      </disk>
      <interface type='bridge'>
        <model type='virtio'/>
        <source bridge="bridge1"/>
        <mac address='$mac' />
      </interface>
      <console type='nmdm'>
      <source master='/dev/nmdm${nmdm}A' slave='/dev/nmdm${nmdm}B'/>
      <target type='serial' port='0'/>
    </console>
    </devices>
</domain>
EOF

cp $image $vmdir/$vmname.img

sudo virsh define $libvirt_tmp

if [ $? != 0 ]
then
	exit 1
fi

rm $libvirt_tmp
mkdir -p /var/log/vmlogs/$vmname
AddHostEntry $vmname ${nmdm}

